project_name: accuknox

builds:
  - binary: accuknox
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -w -s -X github.com/accuknox/accuknox-cli/selfupdate.BuildDate={{.Date}} -X github.com/accuknox/accuknox-cli/selfupdate.GitSummary={{.Version}}
    env:
      - CGO_ENABLED=0


